from linked_list import LinkedList

l = LinkedList()

#print(f"esta vacia? {l.is_empty()}")
l.append(10)
l.append(5)
l.append(6)
l.append(20)
#print(f"esta vacia? {l.is_empty()}")
l.transversal()
#l.remove(6)
#l.transversal()
#l.remove(10)
#l.transversal()
#l.preppend(12)
#l.transversal()
#x = l.tail()
#print(x.data)
print(l.get(10))